//! Trait for models that can be serialized and deserialized by Kiota.

use std::any::Any;
use std::collections::HashMap;

use crate::api_error::ApiError;
use crate::parse_node::ParseNode;
use crate::serialization_writer::SerializationWriter;

/// A closure that deserializes a single field from a [`ParseNode`] into a [`Parsable`] model.
pub type FieldDeserializer = Box<dyn Fn(&mut dyn Parsable, &dyn ParseNode) + Send + Sync>;

/// Implemented by every model generated by Kiota.
///
/// Provides field-level deserialization callbacks and a serialization method.
/// This trait is dyn-compatible — no generic methods.
pub trait Parsable: Send + Sync {
    /// Returns a map of field names to deserialization closures.
    ///
    /// Each closure receives a reference to `dyn ParseNode` positioned on the
    /// field value and is responsible for assigning the parsed value to `self`.
    ///
    /// NOTE: This takes `&mut self` so closures can mutate the model. The
    /// closures capture a raw pointer to self for interior mutation.
    fn get_field_deserializers(&self) -> HashMap<String, FieldDeserializer>;

    /// Serializes `self` into the given [`SerializationWriter`].
    fn serialize(&self, writer: &mut dyn SerializationWriter) -> Result<(), ApiError>;

    /// Downcast to `Any` for type recovery after deserialization.
    fn as_any(&self) -> &dyn Any;

    /// Mutable downcast to `Any` for type recovery.
    fn as_any_mut(&mut self) -> &mut dyn Any;
}

/// A factory function that creates a default boxed [`Parsable`] instance.
///
/// Used by the infrastructure to construct model objects during deserialization
/// before their fields are populated.
pub type ParsableFactory = Box<dyn Fn() -> Box<dyn Parsable> + Send + Sync>;
